name: "#NPOFailConf"
description: "South Africa’s first non-profit failure conference"

url: http://localhost:4000
baseurl: /npofail

paginate: 10

markdown: kramdown
permalink: pretty
highlighter: pygments